version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/GloiathNationalBank.Common"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/GloiathNationalBank.Services"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/GloiathNationalBank.Storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/GloiathNationalBank.Test"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/GloiathNationalBank.WebApi"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily