name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore Packages
        run: nuget restore GloiathNationalBank.sln

      - name: Build solution
        run: msbuild GloiathNationalBank.sln -t:rebuild -property:Configuration=Release
